# Generated by Django 4.0.3 on 2023-01-06 10:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID FOR THIS PARTICULAR BOOK ACROSSS WHOLE LIBRARY', primary_key=True, serialize=False),
        ),
    ]
